repos:

# Automatic source code formatting
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    args: [--safe, --quiet]

# Syntax check and some basic flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-ast
  - id: flake8
    args: ['--max-line-length=88', '--select=W291,W292,W293,F401']
