sudo: false # use containers

language: python
python:
  - "2.7"

addons:
  mariadb: '10.1'
  
before_install:
- mysql -u root -e "CREATE DATABASE ispybtest;"
- mysql -u root -D ispybtest < conf/schema.sql

before_script:
- cp conf/defaults.example.cfg conf/defaults.cfg

# command to install dependencies
install:
- pip install -Iv mysql-connector==2.1.6
  
script:
- cd tests && nosetests -v
