sudo: false # use containers

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  mariadb: '10.2'

before_install:
- mysql -u root -e "CREATE DATABASE ispybtest; SET GLOBAL log_bin_trust_function_creators=ON;"
- mysql -u root -D ispybtest < conf/schema.sql

before_script:
- cp conf/config.example.cfg conf/config.cfg
- cp conf/ws_config.example.cfg conf/ws_config.cfg

install:
- pip install .
- pip install coveralls

script:
- coverage run --source=ispyb setup.py test
after_success: coveralls
