apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ispyb-api
  description: >
    Python package for reading and writing acquisition and processing results
    into an ISPyB database via stored procedures or SQLAlchemy models.
  annotations:
    github.com/project-slug: DiamondLightSource/ispyb-api
  tags:
    - python
  links:
    - url: https://ispyb.readthedocs.io/
      title: Documentation
spec:
  type: library
  lifecycle: production
  owner: group:data-analysis
  dependsOn:
    - resource:ispyb-database
