#!/bin/bash -eu

echo "##[section]Setting up git configuration"
git config --global user.name "ISPyB-API Azure build"
git config --global user.email "DiamondLightSource-build-server@users.noreply.github.com"
git config credential.helper "store --file=.git/credentials"
echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
echo

echo "##[section]Check for existing pull request"
echo $( gh pr list -B ${BRANCH} -H orm-update ) | grep orm-update && {
  echo Pull request already exists. Stopping here.
  exit
} || {
  echo No existing pull request found
}
echo

echo "##[section]Creating commit on branch 'orm-update'"
git checkout -b orm-update
git add src/ispyb/sqlalchemy/_auto_db_schema.py
cat >commit-message <<EOF
Update ISPyB ORM schema to database schema v${DATABASE_SCHEMA}

Generated with
EOF
pip list | grep "SQLAlchemy\|sqlacodegen" >>commit-message
git commit --file=commit-message
git log -2
echo

echo "##[section]Creating pull request"
git push -f --set-upstream origin orm-update
(
set -x
gh pr create -B ${BRANCH} -H orm-update -t "ISPyB ORM schema update v${DATABASE_SCHEMA}" -b "
This is an automated pull request to update the ISPyB ORM schema.

Before merging this pull request you may want to
* [ ] ensure tests pass
* [ ] update \`HISTORY.rst\` to reflect the changes in this pull request
"
)
echo
