#!/bin/bash -eu

echo "##[section]Setting up git configuration"
git config --global user.name "ISPyB-API Azure build"
git config --global user.email "DiamondLightSource-build-server@users.noreply.github.com"
git config credential.helper "store --file=.git/credentials"
echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
echo

echo "##[section]Installing github cli"
pushd .. >/dev/null
wget -nv https://github.com/github/hub/releases/download/v2.6.0/hub-linux-amd64-2.6.0.tgz -O - | tar xz
export PATH=$(pwd)/hub-linux-amd64-2.6.0/bin/:${PATH}
popd >/dev/null
hub --version
echo

echo "##[section]Check for existing pull request"
hub pr list -b master -f '%H%n' | grep "^orm-update$" && {
  echo Pull request already exists. Stopping here.
  exit
} || {
  echo No existing pull request found
}
echo

echo "##[section]Creating commit on branch 'orm-update'"
git checkout -b orm-update
git add src/ispyb/sqlalchemy/_auto_db_schema.py
cat >commit-message <<EOF
Update ISPyB ORM schema to database schema v${DATABASE_SCHEMA}

Generated with
EOF
pip list | grep "SQLAlchemy\|sqlacodegen" >>commit-message
git commit --file=commit-message
git log -2
echo

# Stop here. It looks like sqlacodegen does not create deterministic output.
# Need to watch this for a while before we can enable automatic PRs.
exit

echo "##[section]Creating pull request"
git push -f --set-upstream origin orm-update
hub pull-request -f -m "ISPyB ORM schema update v${DATABASE_SCHEMA}

This is an automated pull request to update the ISPyB ORM schema.
The update may be caused by a schema update and/or by updates of the SQLAlchemy
or sqlacodegen packages, or a change in the respository pre-commit settings.

Before merging this pull request you may want to
* [ ] ensure tests pass
* [ ] update `HISTORY.rst` to reflect the changes in this pull request
"
echo
